// Auto-generated from web_ui.html.
// DO NOT EDIT.

library ice_code_editor;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:ice_code_editor/ice.dart' as ICE;
import 'package:web_ui/web_ui.dart';



      class IceCodeEditor extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("ice-code-editor");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
      <!-- Placeholder for template. Live elements added to BODY. -->
    ''');
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("ice-code-editor");
    setScopedCss("ice-code-editor", new autogenerated.ScopedCssMapper({"ice-code-editor":"[is=\"ice-code-editor\"]"}));
    _css = getScopedCss("ice-code-editor");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = null;
  }

  /** Original code from the component. */

        ICE.Editor ice;
        String content;

        created() {
          id = 'ice';
          style
           ..width = '600px'
           ..height = '400px';

          content = innerHtml.
            replaceFirst(new RegExp(r'^\s*<!--\s*', multiLine: true), '').
            replaceFirst(new RegExp(r'\s*-->\s*$', multiLine: true), '');
        }

        inserted() {
          ice = new ICE.Editor('#ice');
          ice.content= content;
        }
      }
    
//# sourceMappingURL=web_ui.html_ice_code_editor.dart.map