// Auto-generated from web_ui.html.
// DO NOT EDIT.

library web_ui_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'web_ui.html_ice_code_editor.dart';


// Original code
main(){
}
// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(__root);
  __e0 = __root.nodes[1];
  __t.component(new IceCodeEditor()..host = __e0);
  __t.create();
  __t.insert();
}

//# sourceMappingURL=web_ui.html.dart.map