// Auto-generated from web_ui.html.
// DO NOT EDIT.

library x_ice_code_editor;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:ice_code_editor/ice.dart' as ICE;
import 'package:web_ui/web_ui.dart';



      class XIceCodeEditor extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("x-ice-code-editor");
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("x-ice-code-editor");
    setScopedCss("x-ice-code-editor", new autogenerated.ScopedCssMapper({"x-ice-code-editor":"[is=\"x-ice-code-editor\"]"}));
    _css = getScopedCss("x-ice-code-editor");
    __t = new autogenerated.Template(__root);
    var __binding1 = __t.contentBind(() =>  el , false);
    __root.nodes.addAll([new autogenerated.Text('\n      '),
        __binding1,
        new autogenerated.Text('\n    ')]);
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = null;
  }

  /** Original code from the component. */

        Full ide_lite;
        XIceCodeEditor() {
          ide_lite = new ICE.Full();
        }
        get el => ide_lite.el;
      }
    
//# sourceMappingURL=web_ui.html_x_ice_code_editor.dart.map